name: Unit Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: test
      uses: cedrickring/golang-action@1.3.0
      env:
        GO111MODULE: "on"
      run: |
        go test ./...
