name: Unit Tests

on: push

jobs:
  test:
    name: Run the unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go environment
      uses: actions/setup-go@v1
      with:
        go-version: '1.12'
      env:
        GO111MODULE: "on"
    - uses: actions/checkout@master
    - run: go test ./... -v -cover
